sudo: required
services:
  - docker

before_install:
  - docker build -t sdmiller7/docker-react -f Dockerfile.dev .

script:
  - docker run sdmiller7/docker-react npm run testCI

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-089710905436"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
